### PR TITLE
Update guide_grid.rb

### PR DESCRIPTION
**Pull request by brotuser**
Add Subdivisions

### CODE REVIEW

**Comment by thomthom** [comment]
Ah, sorry man. I though you saw my message on the forum - that I'd already added your code snippet.  I just mentioned GitHub as a future suggestion - sorry, I should have been more clear.

However, have uploaded v0.2 which include your code snippet. So now the user can configure the grid upon creating. I also added the option to adjust it after the fact from the context menu.

Appreciate the contribution! :+1:

**Comment by thomthom** [comment]
I'm not able to automatically merge this pull request, can you pull the latest changes into your fork?

**Comment by thomthom** [comment]
@brotuser : do you need assistance syncing your branch up with this one?

**Comment by brotuser** [comment]
oh sorry dude :D just saw this.... haven't checkt my mail. will report back after work. in like 3-4 hours.

**Comment by thomthom** [comment]
No worries. Take your time. I just wanted to check if you were stuck. I didn't know how experienced with git you were.

**Comment by brotuser** [comment]
I'll just recreate my fork and redo my changes for now. can't auto sync for some reason.
btw as I never used ruby before the globals in guide_grid get initialised by the require statement in core.rb right?

**Pull request closed without merging**
